In [38]:
import tensorflow as tf

In [39]:
x1 = tf.random.uniform([32,10,100,3],minval=-10,maxval=10,dtype=float)
x2 = tf.random.uniform([32,10,100,3],minval=-10,maxval=10,dtype=float)
print(x1)

tf.Tensor(
[[[[ 2.40356445e+00 -4.95344639e+00  4.31942940e-01]
   [-7.42310286e+00  5.35939693e+00 -8.57207108e+00]
   [ 3.94438744e+00  1.19258404e+00  4.46169376e+00]
   ...
   [-5.24908066e+00 -9.90495682e+00 -1.58611774e+00]
   [ 3.27727509e+00  7.90373039e+00 -3.14481020e+00]
   [-1.80313110e+00  5.36260414e+00 -7.60531664e+00]]

  [[ 1.17156982e+00  9.28787613e+00  6.07002258e-01]
   [-2.28600740e+00  5.18489361e+00  4.50927734e+00]
   [ 4.30738449e-01  3.67147923e+00  8.78847122e+00]
   ...
   [ 9.02821541e+00  3.97335052e+00 -1.25489998e+00]
   [-6.94035769e+00  9.91026115e+00 -4.26774979e+00]
   [-4.91026878e+00 -2.12049484e+00  9.57437515e+00]]

  [[-1.76620483e-03 -4.21512842e+00 -1.22589302e+00]
   [-6.55038834e-01  9.40136719e+00  8.58302116e+00]
   [ 3.52529526e+00 -2.74135590e-01  5.95906734e+00]
   ...
   [-2.08969593e+00 -2.17834473e+00  1.25681877e+00]
   [ 6.47271729e+00 -8.58755589e+00 -5.62121391e+00]
   [-2.82342196e+00  1.11954498e+00  9.42004967e+00]]

  ...

 

In [49]:
tavolsag1 = tf.math.reduce_euclidean_norm(
    x1-x2,axis = -1)
print(tavolsag1) #először erre gondoltam de itt a dimenzió nem megfelelő

tf.Tensor(
[[[13.578033  11.24236    7.819841  ... 17.606419   9.39625   16.445522 ]
  [11.59153   10.335794   2.5786679 ...  6.498413  10.712094  14.995265 ]
  [ 5.276503  12.445537  11.514596  ...  8.789353  21.39598   11.773002 ]
  ...
  [18.37992    9.172876  18.031664  ... 19.435349  14.030621  10.716168 ]
  [17.899624  17.826225  13.462128  ... 10.793867  15.550742  12.396607 ]
  [ 8.791824  13.503108  13.5434    ...  7.056888  12.682938   9.64644  ]]

 [[20.934109  20.582767  11.866494  ... 15.397449  12.206703   8.377615 ]
  [10.15932   22.52532   10.494449  ... 10.133397  13.131548   3.392451 ]
  [11.253255  17.356112   8.643492  ... 12.861952  15.866057  14.911297 ]
  ...
  [14.307049  15.150034  22.416481  ...  8.630887  20.647339  19.290583 ]
  [18.494331  12.45033   11.090426  ...  7.581161  18.197544   2.7118158]
  [10.7521305 18.42678    3.3113534 ... 13.502794  18.328539  14.721624 ]]

 [[15.554818   7.401636  15.937796  ... 17.585453  11.43721   20.938547 ]
  [17.57184

In [47]:
def lastdimdist(X,Y):
    Xnew = tf.expand_dims(X, axis=3) 
    Ynew = tf.expand_dims(Y, axis=2) 
    tavolsag = tf.math.reduce_euclidean_norm(
    Xnew-Ynew,axis=-1
    )
    return tavolsag
    #itt a tenzorokat expendelve a megfelelő indexek egymásból vonódnak ki

In [50]:
print(lastdimdist(x1,x2))

tf.Tensor(
[[[[13.578033  11.003193   6.822645  ...  9.544789   8.216855
     5.1340423]
   [12.541599  11.24236   22.03918   ... 15.602737  16.448906
    19.86683  ]
   [10.021233  13.519552   7.819841  ...  8.093313   9.5921755
     4.5959797]
   ...
   [16.886267   8.331645  15.675411  ... 17.606419  15.991228
    13.229053 ]
   [10.652759  15.59205   14.739492  ...  6.2684927  9.39625
    13.9211645]
   [11.658955  12.33185   17.70519   ... 10.2079935 11.345845
    16.445522 ]]

  [[11.59153   13.328618  11.951286  ...  4.3016996  9.289907
     7.676025 ]
   [ 8.4658165 10.335794   6.487406  ...  9.951838   4.070943
     9.047965 ]
   [ 4.313864  14.867606   2.5786679 ... 12.5457115  7.5570784
     7.7890286]
   ...
   [11.304653  18.876133  14.450848  ...  6.498413  16.737743
     6.896434 ]
   [18.959028   8.6471615 17.388079  ... 11.61858   10.712094
    16.859392 ]
   [ 9.725901  13.167395   5.6565366 ... 18.292694   9.354592
    14.995265 ]]

  [[ 5.276503   9.313239   5.16917